### PR TITLE
Small fixes

### LINKED ISSUE #45: Cleanup mock data
Repository browsing and permissions were previously based on pure mocked data. This data and leftover attached functions need to be identified and removed.

### PR DESCRIPTION
**Pull request by mpsonntag**
This pull request closes #45, #48 and #59.

### CODE REVIEW

File: src/js/comp/account/Repos.vue [hunk 1]
```diff
@@ -5,12 +5,12 @@
...
-            <div>
+            <span>
                 <ul class="nav pull-right" v-if="account_is_owner">
                     <li role="presentation">
-                        <button class="btn btn-default">
-                            <router-link :to="{ name: 'repository-create'}">New Repository</router-link>
-                        </button>
+                        <router-link :to="{ name: 'repository-create'}" class="btn btn-default">
+                            New Repository
+                        </router-link>
```
Comment (achilleas-k) [inline src/js/comp/account/Repos.vue:13]: yay

**Review by achilleas-k — APPROVED** [review]
